// corpus-format.mjs — module-bucketing + summary writer.
//
// Mirrors browser-target/scripts/node-corpus-runner.mjs `writeJsonResults` so
// the WebContainer output diffs 1:1 against the edgejs corpus/full results.
// Self-contained: WebContainer has no per-test known-failures manifest, so the
// knownFail* fields are present (schema parity) but always 0. Adds a `skip`
// dimension that the edgejs runner lacks (real `node` exits surface skips).

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

// Extract the module-family bucket from a test filename. Copied verbatim from
// the edgejs runner (node-corpus-runner.mjs:bucketFor) so bucket names match.
//   test-fs-promises-readfile.js → fs_promises
//   test-event-emitter-foo.js    → events
//   test-zlib-bytes-read.js      → zlib
export function bucketFor(name) {
  const body = name.replace(/^test-/, "").replace(/\.(js|mjs|cjs)$/, "");
  const multiWord = [
    ["async-hooks-", "async_hooks"],
    ["perf-hooks-", "perf_hooks"],
    ["child-process-", "child_process"],
    ["string-decoder-", "string_decoder"],
    ["diagnostics-channel-", "diagnostics_channel"],
    ["trace-events-", "trace_events"],
    ["readline-promises-", "readline_promises"],
    ["fs-promises-", "fs_promises"],
    ["timers-promises-", "timers_promises"],
  ];
  for (const [prefix, bucket] of multiWord) {
    if (body.startsWith(prefix)) return bucket;
  }
  if (body.startsWith("event-") || body.startsWith("events-") || body === "events") return "events";
  if (body.startsWith("worker-")) return "worker_threads";
  const m = /^([a-z][a-z0-9]*)(?:-|$)/.exec(body);
  return m ? m[1] : "_misc";
}

function aggregateByBucket(results) {
  const buckets = new Map();
  for (const r of results) {
    const b = bucketFor(r.test);
    let agg = buckets.get(b);
    if (!agg) {
      agg = { bucket: b, pass: 0, fail: 0, timeout: 0, skip: 0, total: 0, failingTests: [] };
      buckets.set(b, agg);
    }
    agg.total++;
    if (r.status === "pass") agg.pass++;
    else if (r.status === "skip") agg.skip++;
    else if (r.status === "timeout") { agg.timeout++; agg.failingTests.push(r.test); }
    else { agg.fail++; agg.failingTests.push(r.test); }
  }
  return [...buckets.values()].sort((a, b) => a.bucket.localeCompare(b.bucket));
}

export function writeJsonResults(jsonPath, results, startedAt, finishedAt) {
  mkdirSync(dirname(jsonPath), { recursive: true });
  const aggregates = aggregateByBucket(results);
  const pass = results.filter((r) => r.status === "pass").length;
  const fail = results.filter((r) => r.status === "fail").length;
  const timeout = results.filter((r) => r.status === "timeout").length;
  const skip = results.filter((r) => r.status === "skip").length;
  const total = results.length;
  const round = (x) => Math.round(x * 10000) / 100;
  const summary = {
    runtime: "stackblitz-webcontainer",
    startedAt,
    finishedAt,
    durationMs: finishedAt - startedAt,
    totalTests: total,
    pass,
    fail,
    timeout,
    skip,
    knownFail: 0,
    knownFailChanged: 0,
    unexpectedPass: 0,
    passRate: total === 0 ? 0 : round(pass / total),
    passRateExclSkip: total - skip === 0 ? 0 : round(pass / (total - skip)),
    perBucket: aggregates.map((a) => ({
      bucket: a.bucket,
      pass: a.pass,
      fail: a.fail,
      timeout: a.timeout,
      skip: a.skip,
      total: a.total,
      passRate: a.total === 0 ? 0 : round(a.pass / a.total),
    })),
    knownFailChangedDetail: [],
    unexpectedPassDetail: [],
    results,
  };
  writeFileSync(jsonPath, JSON.stringify(summary, null, 2) + "\n");
  return summary;
}

export function writeSummaryMd(mdPath, m) {
  const lines = [
    "# Node Test Corpus Pass Rates — StackBlitz WebContainer",
    "",
    "Generated by `run-corpus.mjs` (child_process engine, one real `node` per test).",
    "",
    `* Runtime:    ${m.runtime}`,
    `* Started:    ${new Date(m.startedAt).toISOString()}`,
    `* Finished:   ${new Date(m.finishedAt).toISOString()}`,
    `* Wall clock: ${(m.durationMs / 60000).toFixed(1)} min`,
    `* Total:      ${m.totalTests} (pass ${m.pass} / fail ${m.fail} / timeout ${m.timeout} / skip ${m.skip})`,
    `* Pass rate:  **${m.passRate}%**  (excluding skips: ${m.passRateExclSkip}%)`,
    "",
    "## Per-module pass rates",
    "",
    "| Module | Pass | Fail | Timeout | Skip | Total | Pass rate |",
    "|---|---:|---:|---:|---:|---:|---:|",
    ...m.perBucket.map(
      (b) => `| \`${b.bucket}\` | ${b.pass} | ${b.fail} | ${b.timeout} | ${b.skip} | ${b.total} | ${b.passRate}% |`,
    ),
    "",
  ];
  writeFileSync(mdPath, lines.join("\n") + "\n");
}
